### ISSUE TITLE
最新版fisco bcos v2.6.0的console安装不成功，Unknown named curve: 1.3.132.0.10

### ISSUE THREAD

**Issue by Himan000** [FISCO-BCOS/console#343]
按照https://fisco-bcos-documentation.readthedocs.io/zh_CN/latest/docs/enterprise_tools/tutorial_detail_operation.html文档安装一个节点的generator，generator是成功的。但是安装console后启动console失败。

console日志如下：

[INFO] [2020-09-15 18:48:47] AbstractApplicationContext.prepareRefresh(583) | Refreshing org.springframework.context.support.ClassPathXmlApplicationContext@2437c6dc: startup date [Tue Sep 15 18:48:47 CST 2020]; root of context hierarchy
[INFO] [2020-09-15 18:48:47] XmlBeanDefinitionReader.loadBeanDefinitions(317) | Loading XML bean definitions from class path resource [applicationContext.xml]
[INFO] [2020-09-15 18:48:49] Service.initJavaOpt(296) | set jdk.tls.namedGroups opt, value : secp256k1
[INFO] [2020-09-15 18:48:49] ChannelConnections.init(318) |  all connections: [ConnectionInfo{host='127.0.0.1', port=20200}, ConnectionInfo{host='127.0.0.1', port=20201}]
[INFO] [2020-09-15 18:48:49] ChannelConnections.initSslContext(546) |  ca certificate: ca.crt, sdk certificate: sdk.crt, sdk key: sdk.key
[ERROR] [2020-09-15 18:48:49] ChannelConnections.initSslContext(561) |  Failed to initialize the SSLContext, e: {} 
java.security.cert.CertificateParsingException: java.io.IOException: Unknown named curve: 1.3.132.0.10
	at sun.security.x509.X509CertInfo.<init>(X509CertInfo.java:169)
	at sun.security.x509.X509CertImpl.parse(X509CertImpl.java:1804)
	at sun.security.x509.X509CertImpl.<init>(X509CertImpl.java:195)
	at sun.security.provider.X509Factory.engineGenerateCertificate(X509Factory.java:102)
	at java.security.cert.CertificateFactory.generateCertificate(CertificateFactory.java:339)
	at io.netty.handler.ssl.SslContext.getCertificatesFromBuffers(SslContext.java:1200)
	at io.netty.handler.ssl.SslContext.toX509Certificates(SslContext.java:1189)
	at io.netty.handler.ssl.SslContextBuilder.trustManager(SslContextBuilder.java:242)
	at org.fisco.bcos.channel.handler.ChannelConnections.initSslContext(ChannelConnections.java:554)
	at org.fisco.bcos.channel.handler.ChannelConnections.startConnect(ChannelConnections.java:344)
	at org.fisco.bcos.channel.client.Service.run(Service.java:332)
	at console.ConsoleInitializer.init(ConsoleInitializer.java:121)
	at console.ConsoleClient.main(ConsoleClient.java:45)
Caused by: java.io.IOException: Unknown named curve: 1.3.132.0.10
	at sun.security.ec.ECParameters.engineInit(ECParameters.java:143)
	at java.security.AlgorithmParameters.init(AlgorithmParameters.java:293)
	at sun.security.x509.AlgorithmId.decodeParams(AlgorithmId.java:132)
	at sun.security.x509.AlgorithmId.<init>(AlgorithmId.java:114)
	at sun.security.x509.AlgorithmId.parse(AlgorithmId.java:372)
	at sun.security.x509.X509Key.parse(X509Key.java:168)
	at sun.security.x509.CertificateX509Key.<init>(CertificateX509Key.java:75)
	at sun.security.x509.X509CertInfo.parse(X509CertInfo.java:667)
	at sun.security.x509.X509CertInfo.<init>(X509CertInfo.java:167)
	... 12 more
[ERROR] [2020-09-15 18:48:49] Service.run(386) |  service init failed, error message:  Failed to initialize the SSLContext: Input stream does not contain valid certificates., error: 
javax.net.ssl.SSLException:  Failed to initialize the SSLContext: Input stream does not contain valid certificates.
	at org.fisco.bcos.channel.handler.ChannelConnections.initSslContext(ChannelConnections.java:562)
	at org.fisco.bcos.channel.handler.ChannelConnections.startConnect(ChannelConnections.java:344)
	at org.fisco.bcos.channel.client.Service.run(Service.java:332)
	at console.ConsoleInitializer.init(ConsoleInitializer.java:121)
	at console.ConsoleClient.main(ConsoleClient.java:45)
[ERROR] [2020-09-15 18:48:49] ConsoleInitializer.init(123) |  message:  Failed to initialize the SSLContext: Input stream does not contain valid certificates., e: {}
javax.net.ssl.SSLException:  Failed to initialize the SSLContext: Input stream does not contain valid certificates.
	at org.fisco.bcos.channel.handler.ChannelConnections.initSslContext(ChannelConnections.java:562)
	at org.fisco.bcos.channel.handler.ChannelConnections.startConnect(ChannelConnections.java:344)
	at org.fisco.bcos.channel.client.Service.run(Service.java:332)
	at console.ConsoleInitializer.init(ConsoleInitializer.java:121)
	at console.ConsoleClient.main(ConsoleClient.java:45)

请问这个问题如何解？谢谢！

**Comment by Himan000** [comment]
问题已解决。
JDK问题，安装合适的JDK即可。

**Comment by Himan000** [comment]
感慨一下：比较失望的是，fisco的支持比较差，一般给出的问题无人回应。多数情况只能自己看源码解决。虽然源码不难，但是时间有限。希望这个问题fisco能改善，否则也只能自己玩了。
