### ISSUE TITLE
solidity中使用using语法的合约，生成java类时报错。

### ISSUE THREAD

**Issue by limingxie** [FISCO-BCOS/console#821]
#### ExtraProp.sol
```sol
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.7;

library ExtraProp {
    struct Prop {
        uint256 bit;
    }
}
```

#### ExtraPropFunc.sol
```sol
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.7;

import {ExtraProp} from "./ExtraProp.sol";

library ExtraPropFunc {
    function bitLook(ExtraProp.Prop storage self, uint256 look) public view returns (bool){
        return self.bit & look == look;
    }
}
```

#### HasExtraProp.sol
```sol
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.7;

import {ExtraProp} from "./ExtraProp.sol";
import {ExtraPropFunc} from "./ExtraPropFunc.sol";

contract HasExtraProp{
    ExtraProp.Prop public prop;
    using ExtraPropFunc for ExtraProp.Prop;

    function getProp() external view returns (ExtraProp.Prop memory){
        return prop;
    }

    function bitLook(uint256 look) external view returns (bool){
        return prop.bitLook(look);
    }
}
```
操作步骤：
1. 先部署 ExtraPropFunc.sol 合约得到 
  合约地址是：0xc9d470c735e10acd45406fb2ef3c73e0f010c4bd
2. 生成HasExtraProp.sol Java类的时候出错。

```bash
# 使用--libraries 参数
$ bash contract2java.sh  solidity -s ./contracts/solidity/HasExtraProp.sol --libraries ExtraPropFunc:0xc9d470c735e10acd45406fb2ef3c73e0f010c4bd -p com.dfh.bcos
*** Compile solidity HasExtraProp.sol*** 
*** Analysis evm bytecode HasExtraProp.sol failed *** 
 error: Traceback (most recent call last):
  File "generatefacts", line 64, in <module>
  File "generatefacts", line 25, in main
  File "src/blockparse.py", line 163, in __init__
ValueError: non-hexadecimal number found in fromhex() arg at position 418
[19487] Failed to execute script 'generatefacts' due to unhandled exception!
```

```bash
# 加上 -n 的选项
$ bash contract2java.sh  solidity -s ./contracts/solidity/HasExtraProp.sol -l ExtraPropFunc:0xc9d470c735e10acd45406fb2ef3c73e0f010c4bd -n -p com.dfh.bcos
*** Compile solidity HasExtraProp.sol*** 
Compile binary for HasExtraProp failed, The address of the library must be manually set.
If you use the sol2java.sh script, please deploy the library to the blockchain first, and use the -l option to set the contract address of the dependent library
```

使用using语法的sol文件编译后会有 _ 标识 需要的智能合约地址，但是我看源码中好像有 _ 就只能报上述错误。
使用using语法的sol文件是不能生成java类吗？

**Comment by kyonRay** [comment]
在3.0的编译Solidity并生成Java 接口文件中仍然不支持这种写法，建议把library源码引入到合约里。

**Comment by limingxie** [comment]
好的~  明白了~ 谢谢...^^

这个Issue要关掉吗？
